FROM golang:1.11-alpine

RUN apk add --no-cache --update git


WORKDIR /go/src/github.com/demetriuz/domain-expiration-checker/
ADD . /go/src/github.com/demetriuz/domain-expiration-checker/

RUN GOOS=linux GOARCH=amd64 go build -o /artifacts/domain-expiration-checker.linux-amd64 && \
	GOOS=windows GOARCH=amd64 go build -o /artifacts/domain-expiration-checker.windows-amd64.exe && \
	GOOS=darwin GOARCH=amd64 go build -o /artifacts/domain-expiration-checker.darwin-amd64